#!/usr/bin/env bash
# ==============================================================================
# 000-MISSION-CONTROL: AUTOMATED PRODUCTION VPS DEPLOYMENT SCRIPT
# Supported OS: Ubuntu 20.04/22.04/24.04, Debian 11/12, CentOS 8/9, AlmaLinux
# ==============================================================================

set -e

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${CYAN}"
cat << "EOF"
  ██████╗  ██████╗  ██████╗     ███╗   ███╗██╗███████╗███████╗██╗ ██████╗ ███╗   ██╗
 ██╔═████╗██╔═████╗██╔═████╗    ████╗ ████║██║██╔════╝██╔════╝██║██╔═══██╗████╗  ██║
 ██║██╔██║██║██╔██║██║██╔██║    ██╔████╔██║██║███████╗███████╗██║██║   ██║██╔██╗ ██║
 ████╔╝██║████╔╝██║████╔╝██║    ██║╚██╔╝██║██║╚════██║╚════██║██║██║   ██║██║╚██╗██║
 ╚██████╔╝╚██████╔╝╚██████╔╝    ██║ ╚═╝ ██║██║███████║███████║██║╚██████╔╝██║ ╚████║
  ╚═════╝  ╚═════╝  ╚═════╝     ╚═╝     ╚═╝╚═╝╚══════╝╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝
                      MISSION CONTROL // VPS DEPLOYMENT WIZARD
EOF
echo -e "${NC}"

# Check root/sudo permissions
if [[ $EUID -ne 0 ]]; then
   echo -e "${YELLOW}[!] Note: Running as non-root. Sudo may be required for Docker operations.${NC}"
fi

# 1. Check Docker Installation
echo -e "${CYAN}[1/5] Checking Docker & Container Runtime...${NC}"
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}[*] Docker is not installed. Installing official Docker engine...${NC}"
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm -f get-docker.sh
    systemctl enable --now docker || true
    echo -e "${GREEN}[✓] Docker installed successfully.${NC}"
else
    echo -e "${GREEN}[✓] Docker is already installed: $(docker --version)${NC}"
fi

# 2. Check Docker Compose Plugin
if ! docker compose version &> /dev/null; then
    echo -e "${YELLOW}[*] Docker Compose plugin not found. Installing compose plugin...${NC}"
    apt-get update && apt-get install -y docker-compose-plugin || yum install -y docker-compose-plugin || true
fi
echo -e "${GREEN}[✓] Docker Compose ready: $(docker compose version)${NC}"

# 3. Interactive Configuration
echo ""
echo -e "${CYAN}[2/5] Domain and SSL Configuration${NC}"
read -rp "Enter Public Domain Name (e.g., 000.yourdomain.com or 000.localhost) [default: 000.localhost]: " DOMAIN_INPUT
DOMAIN_NAME=${DOMAIN_INPUT:-000.localhost}

read -rp "Enter Admin Email for Let's Encrypt SSL notices [default: admin@${DOMAIN_NAME}]: " EMAIL_INPUT
ADMIN_EMAIL=${EMAIL_INPUT:-admin@${DOMAIN_NAME}}

# 4. Generate .env configuration
echo ""
echo -e "${CYAN}[3/5] Writing environment configuration to .env...${NC}"
cat > .env << EOF
# Generated by deploy-vps.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
DOMAIN_NAME=${DOMAIN_NAME}
ADMIN_EMAIL=${ADMIN_EMAIL}
PORT=3000
EOF
echo -e "${GREEN}[✓] Environment file .env generated successfully.${NC}"

# 5. Build and Start Container Stack
echo ""
echo -e "${CYAN}[4/5] Building production images and launching containers...${NC}"
docker compose down --remove-orphans 2>/dev/null || true
docker compose up -d --build

# 6. Verify Health Status
echo ""
echo -e "${CYAN}[5/5] Waiting for services to become healthy...${NC}"
sleep 4

if docker compose ps | grep -q "healthy\|running"; then
    echo ""
    echo -e "${GREEN}========================================================================${NC}"
    echo -e "${GREEN}   🚀 000-MISSION-CONTROL DEPLOYED SUCCESSFULLY ON VPS!                 ${NC}"
    echo -e "${GREEN}========================================================================${NC}"
    echo ""
    echo -e "  🌐 Dashboard URL:    ${CYAN}https://${DOMAIN_NAME}${NC}"
    if [[ "$DOMAIN_NAME" == "000.localhost" || "$DOMAIN_NAME" == "localhost" ]]; then
      echo -e "  🌐 Local Fallback:  ${CYAN}http://localhost:80${NC}"
    fi
    echo -e "  🔒 Security Engine:  ${GREEN}WebCrypto AES-GCM-256 (Zero-Knowledge)${NC}"
    echo -e "  📡 Edge Proxy:       ${GREEN}Caddy 2.8 with Auto-SSL & HTTP/3 QUIC${NC}"
    echo -e "  📁 Containers:       ${CYAN}000_app (Nginx), 000_caddy (Proxy)${NC}"
    echo ""
    echo -e "Useful Commands:"
    echo -e "  • View live logs:     ${YELLOW}docker compose logs -f${NC}"
    echo -e "  • Restart stack:      ${YELLOW}docker compose restart${NC}"
    echo -e "  • Rolling update:     ${YELLOW}./scripts/update-vps.sh${NC}"
    echo -e "  • Stop all:           ${YELLOW}docker compose down${NC}"
    echo ""
else
    echo -e "${RED}[!] Warning: One or more containers failed to start. Check logs via: docker compose logs${NC}"
fi
